services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev

    working_dir: /app
    # Mount source for hot reload + persist node_modules separately
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules

    environment:
      NODE_ENV: development
      # Prisma dev schema typically points to env("DATABASE_URL")
      # Use SQLite file in repo for convenience:
      DATABASE_URL: "file:./prisma/dev.db"
      # Improve file watching inside Docker on some hosts
      CHOKIDAR_USEPOLLING: "true"
      PORT: "3000"
    ports:
      - "3000:3000"
    # Install deps, generate dev Prisma client, run Next dev server
    command: >
      sh -c "
        npm ci &&
        npm run db:migrate:development &&
        npm run dev
      "
    # Faster container networking + predictable restarts
    restart: unless-stopped

volumes:
  app_node_modules:
