sonar.projectKey=SebastianPegoraro_url-shortener
sonar.organization=sebastianpegoraro

sonar.sources=src
sonar.tests=src

sonar.exclusions=**/node_modules/**,**/.next/**,**/public/**
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclude the generated Swagger file from analysis
sonar.exclusions=src/lib/swagger.ts
sonar.exclusions=src/app/docs/page.tsx
sonar.exclusions=src/app/api/docs/route.ts